[window]
opacity = 0.95

# Default colors
[colors.primary]
background = '#000000'
foreground = '#edecee'

[colors.normal]
black   = '#000000'
red     = '#aa0000'
green   = '#00aa00'
yellow  = '#aa5500'
blue    = '#0000aa'
magenta = '#aa00aa'
cyan    = '#00aaaa'
white   = '#aaaaaa'

[colors.bright]
black   = '#555555'
red     = '#ff5555'
green   = '#55ff55'
yellow  = '#ffff55'
blue    = '#5555ff'
magenta = '#ff55ff'
cyan    = '#55ffff'
white   = '#ffffff'

[colors.selection]
text       = 'CellForeground'
background = '#999999'

[colors.cursor]
cursor = '#ffffff'

[font.offset]
x = 0
y = 0

[font]
size = 10.5

[font.normal]
family = "GohuFont 14 Nerd Font Mono"

[mouse]
bindings = [
    { mouse = "Right", mods = "Control", action = "Copy" },
    { mouse = "Left", mods = "Control", action = "Paste" }
]


[general]
live_config_reload = true
